services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
  keycloak:
    image: wizzn/keycloak:14
    container_name: "keycloak"
    command: ["-Djboss.http.port=${KEYCLOAK_PORT}"]
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:${KEYCLOAK_PORT}/auth
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: ${DB_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init-db-docker.sh:/docker-entrypoint-initdb.d/init-db-docker.sh
    env_file:
      - ./.env

volumes:
  dbdata:
    name: ${DB_VOLUME}
